<?php

/**
 * Tasks
 *
 * @copyright (c) 2009, Fabian Wuertz
 * @author Fabian Wuertz
 * @link http://fabian.wuertz.org
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @package Tasks
 */

class Tasks_Controller_User extends Zikula_Controller
{

    //-----------------------------------------------------------//
    //-- View ---------------------------------------------------//
    //-----------------------------------------------------------//

    /**
    * Main page - Redirect to viewAll
    *
    * @return The view redirect
    */

    public function main()
    {
        return $this->viewAll();
    }

    /**
    * View all categories
    *
    * @return The view var
    */

    public function viewAll()
    {
        // Security check
        if (!SecurityUtil::checkPermission('Tasks::', '::', ACCESS_READ)) {
            return LogUtil::registerPermissionError();
        }

        // Get form/request vars
        $mode = FormUtil::getPassedValue('mode', isset($args['mode']) ? $args['mode'] : null, 'POST');
        if(empty($mode)) $mode = 'undone';

        $tasks = ModUtil::apiFunc('Tasks','user','getTasks', $mode );

        // load the category registry util
        if (!Loader::loadClass('CategoryRegistryUtil')) {
            z_exit(__f('Error! Unable to load class [%s%]', 'CategoryRegistryUtil', $dom));
        }
        $catregistry = CategoryRegistryUtil::getRegisteredModuleCategories('Tasks', 'tasks');

        // Create and return output object
        $this->view->assign('tasks', $tasks);
        $this->view->assign('mode', $mode );
        $this->view->assign('catregistry', $catregistry);
        return $this->view->fetch('user/viewAll.tpl');
    }

    /**
    * View task
    *
    * @param array $args POST/REQUEST vars
    * @return The view var
    */

    public function view()
    {

        // Security check
        if ( !SecurityUtil::checkPermission('Tasks::', '::', ACCESS_READ) ) {
                return LogUtil::registerPermissionError();
        }

        // Get form/request vars
        $tid = FormUtil::getPassedValue('tid', isset($args['tid']) ? $args['tid'] : null, 'REQUEST');	
        $task = ModUtil::apiFunc('Tasks','user','getTask', $tid );

        // Return the output that has been generated by this function
        $this->view->assign($task);
        return $this->view->fetch('user/view.tpl');

    }


    //-----------------------------------------------------------//
    //-- Add/Edit -----------------------------------------------//
    //-----------------------------------------------------------//

    /**
    * Add/Edit a task (gui)
    *
    * @param array $args POST/REQUEST vars
    * @return The view var
    */

    public function modify($args)
    {
        $form = FormUtil::newForm('Tasks', $this);
        return $form->execute('user/modify.tpl', new Tasks_Handler_Modify());
    }

}